### ISSUE TITLE
Why the final result's number is 3744, the validation number is 3769?

### ISSUE THREAD

**Issue by rockywind** [THU17cyz/3DIoUMatch-PVRCNN#13]
Hello, thank you for your codebase!
I am trouble that the final detection result number is consistent with the input number.
````2022-04-14 14:04:05,520   INFO  Generate label finished(sec_per_example: 0.0563 second).
2022-04-14 14:04:05,520   INFO  recall_roi_0.3: 0.000000
2022-04-14 14:04:05,520   INFO  recall_rcnn_0.3: 0.386345
2022-04-14 14:04:05,520   INFO  recall_roi_0.5: 0.000000
2022-04-14 14:04:05,520   INFO  recall_rcnn_0.5: 0.223867
2022-04-14 14:04:05,520   INFO  recall_roi_0.7: 0.000000
2022-04-14 14:04:05,520   INFO  recall_rcnn_0.7: 0.059667
2022-04-14 14:04:05,523   INFO  Average predicted number of objects(3744 samples): 7.316
Traceback (most recent call last):
  File "train.py", line 237, in <module>
    main()
  File "train.py", line 230, in main
    dist_test=dist_train
  File "/tmpnfs/01_3d/02_pl_3d/3DIoUMatch-CaDDN_02/tools/test.py", line 121, in repeat_eval_ckpt
    result_dir=cur_result_dir, save_to_file=args.save_to_file
  File "/tmpnfs/01_3d/02_pl_3d/3DIoUMatch-CaDDN_02/tools/eval_utils/eval_utils.py", line 113, in eval_one_epoch
    output_path=final_output_dir
  File "/tmpnfs/01_3d/02_pl_3d/3DIoUMatch-CaDDN_02/pcdet/datasets/kitti/kitti_dataset_ssl_mono.py", line 435, in evaluation
    ap_result_str, ap_dict = kitti_eval.get_official_eval_result(eval_gt_annos, eval_det_annos, class_names)
  File "/tmpnfs/01_3d/02_pl_3d/3DIoUMatch-CaDDN_02/pcdet/datasets/kitti/kitti_object_eval_python/eval.py", line 675, in get_official_eval_result
    gt_annos, dt_annos, current_classes, min_overlaps, compute_aos, PR_detail_dict=PR_detail_dict)
  File "/tmpnfs/01_3d/02_pl_3d/3DIoUMatch-CaDDN_02/pcdet/datasets/kitti/kitti_object_eval_python/eval.py", line 588, in do_eval
    min_overlaps, compute_aos)
  File "/tmpnfs/01_3d/02_pl_3d/3DIoUMatch-CaDDN_02/pcdet/datasets/kitti/kitti_object_eval_python/eval.py", line 469, in eval_class
    assert len(gt_annos) == len(dt_annos)
AssertionError````

**Comment by yezhen17** [comment]
Can you print out the numbers?

**Comment by rockywind** [comment]
Thank you for your help!
I fixed this issue by setting the drop_last to False.

````
    dataloader = DataLoader(
        dataset, batch_size=batch_size, pin_memory=True, num_workers=workers,
        shuffle=(sampler is None) and training, collate_fn=dataset.collate_batch,
        drop_last=False, sampler=sampler, timeout=0
        # drop_last=True, sampler=sampler, timeout=0
    )
````
