### ISSUE TITLE
hi, thank for your work! if anyone want to generate the new gt_database, and meet this problem, you can solve this by next tips

### ISSUE THREAD

**Issue by JiangZhenW** [THU17cyz/3DIoUMatch-PVRCNN#17]
/home/ji/anaconda3/envs/qiuqiu/lib/python3.6/runpy.py:125: RuntimeWarning: 'pcdet.datasets.kitti.kitti_dataset' found in sys.modules after import of package 'pcdet.datasets.kitti', but prior to execution of 'pcdet.datasets.kitti.kitti_dataset'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/home/ji/anaconda3/envs/qiuqiu/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ji/anaconda3/envs/qiuqiu/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/ji/code/3DIoUMatch-PVRCNN-main/pcdet/datasets/kitti/kitti_dataset.py", line 517, in <module>
    part_split=sys.argv[3]
  File "/data/ji/code/3DIoUMatch-PVRCNN-main/pcdet/datasets/kitti/kitti_dataset.py", line 452, in create_part_dbinfos
    dataset = KittiDataset(dataset_cfg=dataset_cfg, class_names=class_names, root_path=data_path, training=True)
  File "/data/ji/code/3DIoUMatch-PVRCNN-main/pcdet/datasets/kitti/kitti_dataset.py", line 23, in __init__
    dataset_cfg=dataset_cfg, class_names=class_names, training=training, root_path=root_path, logger=logger
  File "/data/ji/code/3DIoUMatch-PVRCNN-main/pcdet/datasets/dataset.py", line 32, in __init__
    ) if self.training else None
  File "/data/ji/code/3DIoUMatch-PVRCNN-main/pcdet/datasets/augmentor/data_augmentor.py", line 26, in __init__
    cur_augmentor = getattr(self, cur_cfg.NAME)(config=cur_cfg)
  File "/data/ji/code/3DIoUMatch-PVRCNN-main/pcdet/datasets/augmentor/data_augmentor.py", line 37, in gt_sampling
    logger=self.logger
  File "/data/ji/code/3DIoUMatch-PVRCNN-main/pcdet/datasets/augmentor/database_sampler.py", line 24, in __init__
    [self.db_infos[cur_class].extend(infos[cur_class]) for cur_class in class_names]
  File "/data/ji/code/3DIoUMatch-PVRCNN-main/pcdet/datasets/augmentor/database_sampler.py", line 24, in <listcomp>
    [self.db_infos[cur_class].extend(infos[cur_class]) for cur_class in class_names]
KeyError: 'Car'

**Comment by JiangZhenW** [comment]
ok, if anybody meets this problem, you can change kitti_dataset.py, in line 452, `dataset = KittiDataset(dataset_cfg=dataset_cfg, class_names=class_names, root_path=data_path, training=True)` to `dataset = KittiDataset(dataset_cfg=dataset_cfg, class_names=class_names, root_path=data_path, training=False)`

**Comment by yezhen17** [comment]
Sorry for the late reply. Glad you figured it out!

**Comment by JiangZhenW** [comment]
> Sorry for the late reply. Glad you figured it out!

but if my method is right? thank you

**Comment by flyflyly** [comment]
> 

I adopt this ,but it is not right

**Comment by yezhen17** [comment]
I think you should take a look at what training=False implies and see if it meets your needs.

**Comment by nomiaro** [comment]
You can try to produce a new split text.
