### ISSUE TITLE
KeyError: 'Car'

### ISSUE THREAD

**Issue by Wayne-Sydney** [THU17cyz/3DIoUMatch-PVRCNN#22]
I encountered such a problem during training and don't know how to solve it. I did not pre-train and used pv_rcnn_ssl.yaml
`
Traceback (most recent call last):
  File "train.py", line 237, in <module>
    main()
  File "train.py", line 151, in main
    total_epochs=args.epochs
  File "/content/drive/MyDrive/3DIoU/3DIoUMatch-PVRCNN/pcdet/datasets/__init__.py", line 53, in build_dataloader
    logger=logger,
  File "/content/drive/MyDrive/3DIoU/3DIoUMatch-PVRCNN/pcdet/datasets/kitti/kitti_dataset_ssl.py", line 25, in __init__
    dataset_cfg=dataset_cfg, class_names=class_names, training=training, root_path=root_path, logger=logger
  File "/content/drive/MyDrive/3DIoU/3DIoUMatch-PVRCNN/pcdet/datasets/dataset.py", line 32, in __init__
    ) if self.training else None
  File "/content/drive/MyDrive/3DIoU/3DIoUMatch-PVRCNN/pcdet/datasets/augmentor/data_augmentor.py", line 26, in __init__
    cur_augmentor = getattr(self, cur_cfg.NAME)(config=cur_cfg)
  File "/content/drive/MyDrive/3DIoU/3DIoUMatch-PVRCNN/pcdet/datasets/augmentor/data_augmentor.py", line 37, in gt_sampling
    logger=self.logger
  File "/content/drive/MyDrive/3DIoU/3DIoUMatch-PVRCNN/pcdet/datasets/augmentor/database_sampler.py", line 24, in __init__
    [self.db_infos[cur_class].extend(infos[cur_class]) for cur_class in class_names]
  File "/content/drive/MyDrive/3DIoU/3DIoUMatch-PVRCNN/pcdet/datasets/augmentor/database_sampler.py", line 24, in <listcomp>
    [self.db_infos[cur_class].extend(infos[cur_class]) for cur_class in class_names]
KeyError: 'Car'
`

**Comment by wayne-wei-guo** [comment]
After I added --dbinfos, the previous problem disappeared. But another one appeared
`Traceback (most recent call last):
  File "train.py", line 237, in <module>
    main()
  File "train.py", line 151, in main
    total_epochs=args.epochs
  File "/content/drive/MyDrive/3DIoU/3DIoUMatch-PVRCNN/pcdet/datasets/__init__.py", line 53, in build_dataloader
    logger=logger,
  File "/content/drive/MyDrive/3DIoU/3DIoUMatch-PVRCNN/pcdet/datasets/kitti/kitti_dataset_ssl.py", line 38, in __init__
    self.sample_index_list = [x.strip().split(' ')[1] for x in open(split_dir).readlines()] if split_dir.exists() else None
  File "/content/drive/MyDrive/3DIoU/3DIoUMatch-PVRCNN/pcdet/datasets/kitti/kitti_dataset_ssl.py", line 38, in <listcomp>
    self.sample_index_list = [x.strip().split(' ')[1] for x in open(split_dir).readlines()] if split_dir.exists() else None
IndexError: list index out of range`

**Comment by wayne-wei-guo** [comment]
> Traceback (most recent call last):
  File "train.py", line 237, in <module>
    main()
  File "train.py", line 151, in main
    total_epochs=args.epochs
  File "/content/drive/MyDrive/3DIoU/3DIoUMatch-PVRCNN/pcdet/datasets/__init__.py", line 53, in build_dataloader
    logger=logger,
  File "/content/drive/MyDrive/3DIoU/3DIoUMatch-PVRCNN/pcdet/datasets/kitti/kitti_dataset_ssl.py", line 38, in __init__
    self.sample_index_list = [x.strip().split(' ')[1] for x in open(split_dir).readlines()] if split_dir.exists() else None
  File "/content/drive/MyDrive/3DIoU/3DIoUMatch-PVRCNN/pcdet/datasets/kitti/kitti_dataset_ssl.py", line 38, in <listcomp>
    self.sample_index_list = [x.strip().split(' ')[1] for x in open(split_dir).readlines()] if split_dir.exists() else None
IndexError: list index out of range

**Comment by Wayne-Sydney** [comment]
I solved this problem, I need to add other configuration files at runtime

**Comment by yezhen17** [comment]
Sorry for the late reply. Glad you figured it out. You problem is similar to #17

**Comment by Wayne-Sydney** [comment]
> Sorry for the late reply. Glad you figured it out. You problem is similar to #17

By the way, I want to ask another question. I don't understand what is the difference between the three configuration files pv_rcnn.yaml, pv_rcnn_ssl.yaml, pv_rcnn_ssl_60.yaml?

**Comment by yezhen17** [comment]
pv_rcnn.yaml is the original config file of PVRCNN, pv_rcnn_ssl.yaml is the config file for our SSL method, pv_rcnn_ssl_60.yaml is merely changing the training schedule based on pv_rcnn_ssl.yaml.
