### ISSUE TITLE
numpy and numba version dependencies

### ISSUE THREAD

**Issue by adv010** [THU17cyz/3DIoUMatch-PVRCNN#26]

**Comment by adv010** [comment]
DO NOT TRY on torch1.1. torch.nn.SyncBatchNorm doesn't exist in torch 1.1, verified by testing on nvcr.io/nvidia/pytorch:19.02-py3

AttributeError: module 'torch.nn' has no attribute 'SyncBatchNorm'
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from train_utils.optimization import build_optimizer, build_scheduler
  File "tools/train_utils/optimization/fastai_optim.py", line 10, in <module>
    bn_types = (nn.BatchNorm1d, nn.BatchNorm2d, nn.BatchNorm3d, nn.SyncBatchNorm)
AttributeError: module 'torch.nn' has no attribute 'SyncBatchNorm'
